general.import =[
"~/.config/alacritty/themes/themes/tokyo-night.toml"
]
[env]
TERM = "xterm-256color"
[window]
padding.x = 5
padding.y = 5

dynamic_title = false
decorations = "None"

opacity = 0.9
blur = true

[font]
normal.family ="Source Code Pro"
size = 10
